#@data/values
#@overlay/match-child-defaults missing_ok=True

---
infraProvider: vsphere
antrea:
  config:
    #! enableUsageReporting: true/false  # recommend to expose

    #! Egress configuration
    egress:
      exceptCIDRs: ["192.1678.0.1"]  # recommend to expose

    serviceCIDR: 10.96.0.0/12
    serviceCIDRv6: null
    trafficEncapMode: encap
    noSNAT: false
    disableUdpTunnelOffload: false
    #! Setting defaultMTU to null since antrea-agent will discover the MTU of the Node's primary interface and
    #! also adjust MTU to accommodate for tunnel encapsulation overhead.
    defaultMTU: null
    tlsCipherSuites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384
    featureGates:
      AntreaProxy: true
      EndpointSlice: false
      AntreaTraceflow: true
      NodePortLocal: true
      AntreaPolicy: true
      FlowExporter: false
      NetworkPolicyStats: false
      Egress: true
      NodeIPAM: false
      AntreaIPAM: false
      ServiceExternalIP: false
      Multicast: false
